chore: Project dependencies update
salesforce/lwc-test pull request #108
Opened 2021-01-12 08:46 UTC by pmdartus

## Details

- Update all the `peerDependencies` to match
- Update all the dependencies versions and move to a `^` version pinning (more details on this below)
- Remove unused packages: `babel-plugin-transform-dynamic-import`, `@babel/template`
- Normalize `license`, `keywords` and `main` fields between projects

**Why moving to `^` versioning pinning?** 
Historically, we decided that using `~` was the safest approach to version dependencies for LWC related projects to prevent unexpected downstream breaking changes. I do think that this project doesn't need to follow the same semantic:
- Jest uses `^` to pin [dependencies](https://github.com/facebook/jest/blob/v26.6.3/packages/jest-cli/package.json) (regardless if the dependency is external to jest or not). Because of this, even if we protect this project from potential Babel breaking change, Jest doesn't. Using `^` better aligns with Jest dependency management.
- Reduces maintenance burden on us for this less critical project.

2021-01-12 21:21 UTC, jodarove requested changes

2021-01-12 21:21 UTC, jodarove commented on packages/@lwc/jest-transformer/src/index.js
> -        babelDynamicImport,
I have doubts about removing this; if `babel-plugin-transform-dynamic-import` is removed, how will components using `import()` work in the jest environment?

2021-01-13 08:35 UTC, pmdartus commented on packages/@lwc/jest-transformer/src/index.js
> -        babelDynamicImport,
You are right @jodarove this plugin is still needed. This is something interesting because the commonjs plugin refers in the documentation that it is [capable to transform `import()` expression](https://babeljs.io/docs/en/babel-plugin-transform-modules-commonjs). I will open a thread on the Babel repro to discuss this.

2021-01-13 18:41 UTC, jodarove commented on packages/@lwc/jest-transformer/src/index.js
> -        babelDynamicImport,
it could be because of [this check](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-modules-commonjs/src/index.js#L132). That being said, I like more this approach: using `@babel/plugin-proposal-dynamic-import` (+modules-commonjs) instead of `babel-plugin-transform-dynamic-import`.

2021-01-13 18:42 UTC, jodarove approved these changes
:shipit:

2021-01-14 09:36 UTC, merged