Jtu/normalize style attr
salesforce/lwc-test pull request #237
Opened 2024-04-04 17:59 UTC by jmsjtu

Split into two commits to make the changes more obvious.

See #236 for class changes.

BREAKING CHANGE: snapshots may change.

W-15365974

2024-04-04 18:09 UTC, nolanlawson commented on test/src/modules/serializer/styleAttr/__tests__/__snapshots__/styleAttr.spec.js.snap
> +    <div />
Let's add tests for `!important` and extra ending `;`s as well, and whitespace around each.

2024-04-04 18:11 UTC, nolanlawson commented on packages/@lwc/jest-serializer/src/clean-element-attrs.js
> +        }
We should probably split on `;` and normalize whitespace for each, since there can be arbitrary whitespace before/after the semicolon.

2024-04-04 18:12 UTC, nolanlawson commented on packages/@lwc/jest-serializer/src/clean-element-attrs.js
> +        }
Also this would be cleaner to go in its own `cleanElementStyle` function/file imo.

2024-04-04 18:32 UTC, nolanlawson commented on packages/@lwc/jest-serializer/src/clean-element-attrs.js
> +        }
Also: this is not going to handle zany things like `content` or `grid-template-areas` which may contain spaces or semicolons in the value, but I'm not sure that that's worth handling. It quickly devolves into prettier/full CSS parsing, and we probably just need a lightweight formatter.

2024-04-04 20:28 UTC, jmsjtu commented on test/src/modules/serializer/styleAttr/__tests__/__snapshots__/styleAttr.spec.js.snap
> +    <div />
Added in the latest commit! 6d6e6ef557f0da3f8ecb578bc3921642caa4ec33

2024-04-04 21:05 UTC, nolanlawson commented on packages/@lwc/jest-serializer/src/clean-element-styles.js
> +        .join(';');
```suggestion
        .split(';')
        .map(_ => _.trim())
        .filter(Boolean)
        .map(_ => `${_};`)
        .join(' ');
```

This avoids the duplicates `;`s at the end.

2024-04-04 21:26 UTC, wjhsf commented on packages/@lwc/jest-serializer/src/clean-element-styles.js
> +        .join(';');
```suggestion
        .split(';')
        .map(_ => `${_.trim()};`)
        .filter(_ => _ !== ';')
        .join(' ');
```

Same but one less loop.

2024-04-04 21:32 UTC, jmsjtu commented on packages/@lwc/jest-serializer/src/clean-element-styles.js
> +        .join(';');
This will also append a ';' at the end of a style:

```html
<div style="  color: blue  "></div>
```

Becomes:

```html
<div style="color: blue;"></div>
```

Empty ';' will be removed as well

```html
<div style=";;"></div>
```
 Becomes:

```html
<div />
```

Just want to double-check, are we trying to normalize the whitespace or the style attribute output?

Asking because it won't exactly line up with what the component author will see in the browser.

2024-04-04 22:36 UTC, nolanlawson commented on packages/@lwc/jest-serializer/src/clean-element-styles.js
> +        .join(';');
Yes, I think we want consistent output. So consistent `;`s at the end, consistent spacing, and just `<div />` if the `style` is semantically empty.

2024-04-04 22:38 UTC, nolanlawson commented on test/src/modules/serializer/styleAttr/__tests__/__snapshots__/styleAttr.spec.js.snap
> +      style="color : blue; text-align : center;"
This one is going to lead to inconsistencies between static/dynamic sadly... Not sure how to solve without a full CSS parse 🤦

2024-04-05 14:43 UTC, nolanlawson commented on test/src/modules/serializer/styleAttr/__tests__/__snapshots__/styleAttr.spec.js.snap
> +      style="color : blue; text-align : center;"
On second thought, we can't use a CSS parser because we've never validated this content, so it could be syntactically invalid and consumers could be relying on that.

I think we should split on `:` as well and normalize that so that it's always in the format:

```
color: red;
```

or

```
color: red !important;
```

2024-04-05 14:50 UTC, nolanlawson commented on test/src/modules/serializer/styleAttr/__tests__/__snapshots__/styleAttr.spec.js.snap
> +      style="color : blue; text-align : center;"
#238

2024-04-05 17:55 UTC, nolanlawson approved these changes

2024-04-05 21:34 UTC, nolanlawson requested changes
See above and #239

2024-04-08 17:10 UTC, nolanlawson approved these changes

2024-04-08 17:11 UTC, merged