Update @salesforce/apex/* imports to return jest.fn()
salesforce/lwc-test pull request #260
Opened 2024-06-04 09:39 UTC by nwcm

After looking for ways to  simplify mocking apex methods in a SFDX project, I found this transformer is applied. However the apex method transforms don't make the imports available within jests. 

This change allows for jests import and use apex methods cleanly without having to mock in each test file. 

This doesn't apply to wired apex methods which would need `createApexTestWireAdapter()`  from [@salesforce/sf](https://github.com/salesforce/sfdx-lwc-jest)

```js
// foo.test.js
import apexMethod from "@salesforce/apex/ApexClass.apexMethod";

describe("c-foo", () => {
  afterEach(() => {
    // resetEnvironment();
  });
  
  
  it("Test mock", async () => {
     apexMethod.mockResolvedValue('value');
  }
}
```

Otherwise any apex method requires

```js 
jest.mock(
  "@salesforce/apex/ApexClass.apexMethod",
  () => {
    return {
      default: jest.fn()
    };
  },
  { virtual: true }
);
```

2024-06-17 19:15 UTC, nolanlawson commented
Thanks for the contribution! Could you clarify: is this a breaking change?

2024-06-17 19:19 UTC, nolanlawson commented
FYI @pozil @Templarian do you have strong opinions about this? Should we just return a `jest.fn()` so that people can mock directly?

2024-06-18 14:31 UTC, pozil commented
I like the idea of having a mock directly but I have not clue about the potential impact of such a change.

2024-07-01 20:16 UTC, nolanlawson requested changes
I don't think this should be a breaking change. It looks reasonable enough to me.

OTOH could we please add documentation for this so that it's more discoverable? A good place would be [this README](https://github.com/salesforce/lwc-test/blob/master/packages/%40lwc/jest-preset/README.md). Thank you! 🙇

2024-07-30 22:27 UTC, nolanlawson approved these changes

2024-07-30 22:38 UTC, nolanlawson requested changes
One small change to account for `injectGlobals=false` and I think this is good to go! https://github.com/nwcm/lwc-test/pull/1

2024-08-02 20:31 UTC, nolanlawson approved these changes
Thanks a bunch! Really appreciate the time you took to add docs and such. 🙇 Will release this in a bit.

2024-08-02 20:31 UTC, merged