Jest snapshot-based approach for SSR testing
salesforce/lwc-test pull request #292
Opened 2024-08-21 01:33 UTC by lesya7

2024-08-22 21:58 UTC, nolanlawson commented on packages/@lwc/jest-jsdom-custom-test-env/package.json
> +        "jest-environment-jsdom": "^29.7.0"
This should be a `peerDependency` since its version is tied to the overall Jest version, and we don't know what version that will be since we support multiple.

2024-08-22 21:58 UTC, nolanlawson commented on packages/@lwc/jest-jsdom-custom-test-env/src/__tests__/jsdom-custom-test-env.test.js
> +        expect(global.testFilePath).toBe(expectedPath);
Do we need the custom environment if the global `__filename` does the same thing?

It's a little more awkward because we would have to pass the filename from the test file into `readSnapshotMarkup`, but I think it might be simpler because we can avoid the custom environment.

2024-08-22 21:58 UTC, nolanlawson commented on packages/@lwc/jest-preset/src/ssr/html-serializer.js
The goal of this file is two things:

1. Pretty-print the HTML so that the snapshots are easier to read
2. Remove some framework-specific attributes that are not interesting to the component author (e.g. `data-lwc-host-mutated`, CSS scope tokens).

The value of #<span></span>2 is debatable, but #<span></span>1 is quite nice since it makes snapshots much easier to debug. I can see a case for disregarding the whole thing, though, since it doesn't really do anything you can't already do with an off-the-shelf prettifier like [jest-serializer-html](https://github.com/algolia/jest-serializer-html).

Either way, changing this behavior for all current SSR users would definitely be a breaking change. (We consider it a breaking change when snapshots change.) Is there a way that the new serializer could be used only for SSR+hydration tests?

2024-08-22 21:58 UTC, nolanlawson commented on packages/@lwc/jest-preset/src/ssr/snapshot-serializer.js
> +        return typeof _value === 'string' && _value.length > 0;
Names like `_value` (with the underscore) are typically used to indicate an unused variable (e.g. to avoid TypeScript lint errors).

2024-08-22 21:58 UTC, nolanlawson commented on packages/@lwc/jest-ssr-snaphot-utils/src/ssr-snapshot-utils.js
> +    expect.addSnapshotSerializer(jestCustomSnapshotSerializer);
Can this be done with configuration instead, i.e. [`snapshotSerializers`](https://jestjs.io/docs/configuration#snapshotserializers-arraystring)? It seems odd to call `addSnapshotSerializer` over and over.

2024-08-22 21:58 UTC, nolanlawson commented on test/package.json
> -    "private": "true",
This is not intended to be a published package.

2024-08-22 21:58 UTC, nolanlawson commented on test/package.json
> +        "@lwc/ssr-snapshot-utils": "16.1.0"
I don't think this is strictly required since this is a monorepo.

2024-08-22 23:47 UTC, lesya7 commented on packages/@lwc/jest-jsdom-custom-test-env/src/__tests__/jsdom-custom-test-env.test.js
> +        expect(global.testFilePath).toBe(expectedPath);
It's just a unit test for my change that makes sure we can get an absolute path to a test suite during execution. In this test I directly access it but it should, also, be accessible from test utils called from a test.

2024-08-22 23:55 UTC, lesya7 commented on packages/@lwc/jest-jsdom-custom-test-env/package.json
> +        "jest-environment-jsdom": "^29.7.0"
Sure, I'll add "jest-environment-jsdom": "^28 || ^29"

2024-08-23 00:01 UTC, lesya7 commented on packages/@lwc/jest-preset/src/ssr/html-serializer.js
It will be utilized with @lwr/preset-ssr and while calling generateAndSnapshotMarkup. Either way it's going to be a breaking change. I'll look into [jest-serializer-html](https://github.com/algolia/jest-serializer-html).

2024-08-23 00:10 UTC, lesya7 commented on packages/@lwc/jest-ssr-snaphot-utils/src/ssr-snapshot-utils.js
> +    expect.addSnapshotSerializer(jestCustomSnapshotSerializer);
In my case it's not quite feasible because I need to use jestCustomSnapshotSerializer to call an API and pass in SSR-generated markup to replace the original snapshot content. If I don't have to override the snapshot content, then tweaking a config is enough.

2024-08-23 02:53 UTC, lesya7 commented on test/package.json
> -    "private": "true",
Oh..Perhaps I removed this line by accident.

2024-08-23 16:58 UTC, nolanlawson commented on packages/@lwc/jest-jsdom-custom-test-env/src/__tests__/jsdom-custom-test-env.test.js
> +        expect(global.testFilePath).toBe(expectedPath);
Right, I understand that this is just for validation. But the fact that `__filename` works at all is, to me, evidence that we don't necessarily need a custom environment.

I did find [this SO post](https://stackoverflow.com/a/63002088) mentioning a custom environment as the solution, but in my own testing `__filename` also works.

2024-08-23 17:00 UTC, nolanlawson commented on packages/@lwc/jest-ssr-snaphot-utils/src/ssr-snapshot-utils.js
> +    expect.addSnapshotSerializer(jestCustomSnapshotSerializer);
I think we can avoid overriding the snapshot content if we use a serializer other than `@lwc/jest-preset/src/ssr/snapshot-serializer.js`. The goal is just to serialize the HTML as-is (or perhaps with pretty-printing), yes?

2024-08-23 17:06 UTC, lesya7 commented on packages/@lwc/jest-jsdom-custom-test-env/src/__tests__/jsdom-custom-test-env.test.js
> +        expect(global.testFilePath).toBe(expectedPath);
I see what you mean.I need to get an absolute path to a test file from the utils, not directly from the test. I don't want a developer to pass in '__filename' from the test suite. So, instead, I want to get the path from the utils. If I use "__filename" from utils, I will get the path to the utils. Let me know if that addresses your concern.

2024-08-23 17:08 UTC, lesya7 commented on packages/@lwc/jest-ssr-snaphot-utils/src/ssr-snapshot-utils.js
> +    expect.addSnapshotSerializer(jestCustomSnapshotSerializer);
I'm working on that.

2024-08-23 18:00 UTC, lesya7 commented on packages/@lwc/jest-preset/ssr/jest-preset.js
> -    snapshotSerializers: [require.resolve('../src/ssr/html-serializer.js')],
Removed the custom serializer and utilized the out-of-the-box "jest-serializer-html".

2024-08-23 18:00 UTC, lesya7 commented on packages/@lwc/jest-ssr-snaphot-utils/src/ssr-snapshot-utils.js
> +function renderAndHashComponent(tagName, Ctor, props = {}, customTestEnv = {}) {
Renamed the function name after its scope has changed.

2024-08-23 18:05 UTC, lesya7 commented on package.json
> +        "prettier": "^2.0.0",
"prettier" v3. doesn't work with inline snapshots. Here is the thread: https://github.com/jestjs/jest/issues/14305. It's going to be fixed in jest v.30. 
Let me know if you want to keep "prettier" v.3 and I would introduce an alias for "prettier" v.2.

2024-08-23 18:06 UTC, lesya7 commented on packages/@lwc/jest-jsdom-custom-test-env/package.json
> +        "jest-environment-jsdom": "^28 || ^29"
Added "jest-environment-jsdom" as a peer dependency.

2024-08-23 18:13 UTC, lesya7 commented on packages/@lwc/jest-ssr-snaphot-utils/src/ssr-snapshot-utils.js
> +    expect.addSnapshotSerializer(jestCustomSnapshotSerializer);
I removed all previously used custom serializers (the one that was replacing some DOM attributes and the one I introduced.)

2024-08-23 21:01 UTC, nolanlawson commented on packages/@lwc/jest-jsdom-custom-test-env/src/__tests__/jsdom-custom-test-env.test.js
> +        expect(global.testFilePath).toBe(expectedPath);
You cannot get the path from the utils unfortunately. Inside of the utils, `__filename` will resolve to the filename of the utils file, not the file that is calling it.

I agree that asking the developer to pass in `__filename` is ugly. However, compared to a custom environment, I think it's less complex and more maintainable.

2024-08-23 21:07 UTC, nolanlawson commented on packages/@lwc/jest-preset/ssr/jest-preset.js
> -    snapshotSerializers: [require.resolve('../src/ssr/html-serializer.js')],
This is still not where I'd like to go with this... Let me explain.

There are two SSR serialization use cases:

1. SSR alone (current solution)
2. SSR+hydration (proposed solution)

For #<span></span>1, you actually want `/src/ssr/html-serializer.js`. It removes LWC-specific framework attributes, and plus it's what customers have historically used, so dropping it would be a breaking change.

For #<span></span>2, you just need the raw HTML (or perhaps raw+prettified). So this is where `jest-serializer-html` is ideal.

I think that trying to serve both use cases in the same preset is going to cause problems. Unless we decide to deprecate `src/ssr/html-serializer.js` entirely and release a breaking change, and point people to `jest-serializer-html`. But in that case, I don't want us to just be a wrapper around `jest-serializer-html`, because then we run the risk of breaking people whenever that dependency changes.

Let me think about this.

2024-08-23 21:08 UTC, nolanlawson commented on package.json
> +        "prettier": "^2.0.0",
Using prettier v2 is fine.

2024-08-23 21:12 UTC, lesya7 commented on packages/@lwc/jest-jsdom-custom-test-env/src/__tests__/jsdom-custom-test-env.test.js
> +        expect(global.testFilePath).toBe(expectedPath);
I checked in with our customer, and he confirmed that he doesn't want to include __filename in every single test. Hence, I had to find a way to compute the path differently. I don't think it's risky as long as all configuration is done in "preset".

2024-08-23 21:28 UTC, lesya7 commented on packages/@lwc/jest-preset/ssr/jest-preset.js
> -    snapshotSerializers: [require.resolve('../src/ssr/html-serializer.js')],
Sure. I have very little context into the existing serializers and their value. My idea was just to capture the formatted SSR-ed markup in SSR workflow. And for the SSR + hydration, just consume it (no need for another custom serializer).

2024-08-23 21:30 UTC, nolanlawson commented on packages/@lwc/jest-jsdom-custom-test-env/src/__tests__/jsdom-custom-test-env.test.js
> +        expect(global.testFilePath).toBe(expectedPath);
I'm sure the customer doesn't want to type extra code... but the maintenance burden has to be considered here. Let's talk about this.

2024-08-23 21:31 UTC, nolanlawson commented on packages/@lwc/jest-preset/src/ssr/html-serializer.js
It doesn't have to be a breaking change if we propose two separate presets.

2024-08-28 18:13 UTC, nolanlawson requested changes
See above comments

2024-08-28 18:13 UTC, nolanlawson commented on jest.config.js
> -        preset: '@lwc/jest-preset',
I would recommend calling it something like `ssr-for-hydration` since otherwise `ssr-client` may be a bit confusing.

2024-08-28 18:13 UTC, nolanlawson commented on jest.config.js
> -            preset: '@lwc/jest-preset/ssr',
This is a breaking change if we're renaming this. Whereas if we avoid renaming it, then it's not a breaking change for existing consumers.

2024-08-28 18:13 UTC, nolanlawson commented on packages/@lwc/jest-preset/ssr-server/jest-preset.js
> +    snapshotSerializers: ['jest-serializer-html'],
If we make `jest-serializer-html` a dependency and include it in this preset, then we are responsible for breaking changes in `jest-serializer-html`.

Given that this package just pretty-prints the HTML... I dunno. If it were me, I would probably just use our own serializer that keeps the HTML as-is. For instance, the existing serializer could have an option to disable the attribute stripping.

I know I mentioned that pretty-printing may be nice, but it's kind of a hassle if we have to distribute a package. Your call though.

2024-09-03 19:51 UTC, lesya7 commented on jest.config.js
> -            preset: '@lwc/jest-preset/ssr',
Could you provide more details? I believe the jest.config.js file is being used only for the tests in the "test" folder and isn't directly utilized in the customers' source code. Changing the preset should be fine as long as the tests still pass.

2024-09-03 19:55 UTC, lesya7 commented on packages/@lwc/jest-preset/ssr-server/jest-preset.js
> +    snapshotSerializers: ['jest-serializer-html'],
I'm satisfied with the current solution. If any new requirements come up, we can certainly revisit it.

2024-09-03 19:58 UTC, lesya7 commented on packages/@lwc/jest-preset/ssr-server/jest-preset.js
> +    snapshotSerializers: ['jest-serializer-html'],
Also, could you elaborate on the scope of existing serializers? Why don't we consume the generated markup as-is?

2024-09-03 20:00 UTC, lesya7 commented on jest.config.js
> -            preset: '@lwc/jest-preset/ssr',
In the next release, we could inform customers that starting from this version, it's recommended they use the latest version.

2024-09-03 20:04 UTC, lesya7 commented on jest.config.js
> -        preset: '@lwc/jest-preset',
Sure.

2024-09-03 22:50 UTC, nolanlawson commented on packages/@lwc/jest-preset/ssr-server/jest-preset.js
> +    snapshotSerializers: ['jest-serializer-html'],
That's a great question. I think originally the goal was to have a very lightweight HTML formatter. I wouldn't be surprised if, when we first wrote, there were no good off-the-shelf options (especially for shadow DOM, which didn't even have an HTML format until [declarative shadow DOM](https://web.dev/articles/declarative-shadow-dom) was standardized.

Meanwhile, we also thought it would be useful to hide framework-internal details to avoid breaking snapshots when the framework changes... but this value is debatable IMO.

2024-09-06 18:06 UTC, nolanlawson commented on packages/@lwc/jest-jsdom-custom-test-env/package.json
> +    "name": "@lwc/jest-jsdom-custom-test-env",
The name `custom` does not really communicate much here. I'd call it `@lwc/jest-environment-for-hydration` (to make it clear that it pairs with the other `-for-hydration` one).

2024-09-06 18:07 UTC, nolanlawson requested changes
I have one last nitpick, then :+1:

2024-09-06 19:54 UTC, nolanlawson approved these changes

2024-09-06 20:04 UTC, merged